In [31]:
import pandas as pd
data =  pd.read_csv('globalterrorismdb_0718dist.csv',encoding = 'ISO-8859-1')

C:\Users\DELL\AppData\Local\Temp\ipykernel_11860\3250236414.py:2: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  data =  pd.read_csv('globalterrorismdb_0718dist.csv',encoding = 'ISO-8859-1')

In [32]:
data.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [33]:
data.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region',
       ...
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],
      dtype='object', length=135)

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Columns: 135 entries, eventid to related
dtypes: float64(55), int64(22), object(58)
memory usage: 187.1+ MB

In [35]:
data.shape

(181691, 135)

In [36]:
columns_to_include = [
    'eventid', 'iyear', 'imonth', 'iday', 'country', 'country_txt', 'region_txt', 
    'city', 'success', 'attacktype1_txt', 'nkill', 'propvalue', 'targtype1_txt', 
    'latitude', 'gname', 'longitude', 'targsubtype1_txt', 'target1', 
    'weaptype1_txt', 'weapdetail'
]
data = data[columns_to_include]

column_rename_map = {
    'eventid': 'Event_id',
    'iyear': 'Year',
    'imonth': 'Month',
    'iday': 'Day',
    'country': 'Country_no',
    'country_txt': 'Country',
    'region_txt': 'Region',
    'city': 'City',
    'propvalue': 'property_value',
    'attacktype1_txt': 'Attack_type',
    'targtype1_txt': 'Target_type',
    'gname': 'group_name',
    'targsubtype1_txt': 'Target_sub_type',
    'target1': 'Target',
    'nkill': 'no_of_kills',
    'weaptype1_txt': 'Weapon_type',
    'weapdetail': 'Weapon_detail'
}

data.rename(columns=column_rename_map, inplace=True)

# Save the selected columns to a new CSV file
data.to_csv("F:/UNT_Classes/Semester-4/Scientific Data Visualization/Projects/5/preprocessed_selected_renamed.csv", index=False)

In [37]:
data.shape

(181691, 20)

In [38]:
data.columns

Index(['Event_id', 'Year', 'Month', 'Day', 'Country_no', 'Country', 'Region',
       'City', 'success', 'Attack_type', 'no_of_kills', 'property_value',
       'Target_type', 'latitude', 'group_name', 'longitude', 'Target_sub_type',
       'Target', 'Weapon_type', 'Weapon_detail'],
      dtype='object')

In [39]:
data.head()

,Event_id,Year,Month,Day,Country_no,Country,Region,City,success,Attack_type,no_of_kills,property_value,Target_type,latitude,group_name,longitude,Target_sub_type,Target,Weapon_type,Weapon_detail
0,197000000001,1970,7,2,58,Dominican Republic,Central America & Caribbean,Santo Domingo,1,Assassination,1.0,NaN,Private Citizens & Property,18.456792,MANO-D,-69.951164,Named Civilian,Julio Guzman,Unknown,NaN
1,197000000002,1970,0,0,130,Mexico,North America,Mexico city,1,Hostage Taking (Kidnapping),0.0,NaN,Government (Diplomatic),19.371887,23rd of September Communist League,-99.086624,"Diplomatic Personnel (outside of embassy, cons...","Nadine Chaval, daughter",Unknown,NaN
2,197001000001,1970,1,0,160,Philippines,Southeast Asia,Unknown,1,Assassination,1.0,NaN,Journalists & Media,15.478598,Unknown,120.599741,Radio Journalist/Staff/Facility,Employee,Unknown,NaN
3,197001000002,1970,1,0,78,Greece,Western Europe,Athens,1,Bombing/Explosion,NaN,NaN,Government (Diplomatic),37.997490,Unknown,23.762728,Embassy/Consulate,U.S. Embassy,Explosives,Explosive
4,197001000003,1970,1,0,101,Japan,East Asia,Fukouka,1,Facility/Infrastructure Attack,NaN,NaN,Government (Diplomatic),33.580412,Unknown,130.396361,Embassy/Consulate,U.S. Consulate,Incendiary,Incendiary

In [40]:
data.isnull().sum()

Event_id                0
Year                    0
Month                   0
Day                     0
Country_no              0
Country                 0
Region                  0
City                  435
success                 0
Attack_type             0
no_of_kills         10313
property_value     142702
Target_type             0
latitude             4556
group_name              0
longitude            4557
Target_sub_type     10373
Target                638
Weapon_type             0
Weapon_detail       67670
dtype: int64

In [41]:
data['City'].fillna('Unknown',inplace = True)
data['Target'].fillna('Unknown',inplace = True)
data['property_value'].fillna(0,inplace = True)
data['no_of_kills'].fillna(0,inplace = True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_11860\1978417041.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['City'].fillna('Unknown',inplace = True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_11860\1978417041.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Target'].fillna('Unknown',inplace = True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_11860\1978417041.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['property_value'].fillna(0,inplace = True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_11860\1978417041.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['no_of_kills'].fillna(0,inplace = True)

In [42]:
data.to_csv("F:/UNT_Classes/Semester-4/Scientific Data Visualization/Projects/5/preprocessed_selected_renamed.csv", index=False)